### ISSUE TITLE
Restrict snippet search within package

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/Jet.jl#3]
For instance:
```
jet> pkg:DataFrames cmd:create
```
Currently only one of those work.

**Comment by vcoutasso** [comment]
Hello @abelsiqueira! I am interested in contributing to this issue and have already started working on it :).

However, it's not clear to me if we should support searches for multiple snippets like so:

```
jet> pkg:Package cmd:Snippet1 cmd:Snippet2
``` 

To this point, I have only considered a maximum of two arguments, and my string parser would disregard the `cmd:Snippet1` bit in my example (currently it only considers the first and last arguments).

**Comment by abelsiqueira** [comment]
Hi @vcoutasso, thanks for the interest. I'm not sure if we want to have two snippets at the same time. I would say that for now, one should be enough. But, if possible, I ask that you `throw` an error if there are some than one `cmd:` or `pkg:`.
