### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/Jet.jl#6]
I usually prefer names starting with `J`, although `TDLR` may make more sense. Suggestions?

**Comment by Nibba2018** [comment]
How about `JLDR`? Julia's TLDR. :laughing:

**Comment by abelsiqueira** [comment]
Jess - Julia Excelent Source of Snippets

**Comment by ParthPant** [comment]
**Jist** as in Gist for Julia

**Comment by Omar-Elrefaei** [comment]
Hi, I thought you might like to know that there is a naming conflict with [JET.jl](https://github.com/aviatesk/JET.jl) the type analysis tool that has been growing quite a bit.

**Comment by abelsiqueira** [comment]
Thanks for pointing it out. I noticed that but I haven't got around to updating this yet. TLDR.jl has been growing on me.

**Comment by Omar-Elrefaei** [comment]
you don't think it is too close to the tldr cli?

I guess maybe that's not a bad thing if their usages don't really overlap.

**Comment by abelsiqueira** [comment]
This is inspired by tldr, so the name is close by choice.

**Comment by abelsiqueira** [comment]
I have chosen to use TLDR.jl, and will update today. Thanks everyone for the help.
